import type { Metadata } from "next";
import { Lato } from "next/font/google";
import "./globals.css";
import { Suspense } from "react";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";

const lato = Lato({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={lato.className}>
        <Navbar />
        <Suspense>
          <main className="max-w-6xl m-auto">{children}</main>
        </Suspense>
        <Footer />
      </body>
    </html>
  );
}
