import type { Metadata } from "next";
import { Lato, Antic_Didone } from "next/font/google";
import "../globals.css";
import { Suspense } from "react";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";

const lato = Lato({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata: Metadata = {
  title: "Oras muna",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <Navbar />
      <Suspense>{children}</Suspense>
      <Footer />
    </>
  );
}
